# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-18 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lake', '0002_auto_20171215_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='AskPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=16)),
                ('time', models.DateTimeField()),
                ('price_per_btc_eur', models.FloatField()),
                ('volume_btc', models.FloatField()),
                ('min_volume_btc', models.FloatField(null=True)),
            ],
        ),
    ]
