# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-18 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lake', '0003_askprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='askprice',
            name='volume_eur',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
