# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-18 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lake', '0004_askprice_volume_eur'),
    ]

    operations = [
        migrations.AddField(
            model_name='askprice',
            name='is_express',
            field=models.NullBooleanField(),
        ),
    ]
