# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-23 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lake', '0006_yubikey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='askprice',
            name='time',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='rate',
            name='time',
            field=models.DateTimeField(db_index=True),
        ),
    ]
