# Generated by Django 2.0 on 2017-12-25 00:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lake', '0008_auto_20171224_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='TurnOver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('desc', models.CharField(max_length=256)),
                ('new_balance', models.FloatField()),
                ('unique', models.CharField(max_length=64)),
                ('created_at', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
