# Generated by Django 2.0 on 2017-12-25 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lake', '0009_turnover'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TurnOver',
            new_name='BankTransaction',
        ),
    ]
