# Generated by Django 2.0 on 2017-12-25 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lake', '0010_auto_20171225_0107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banktransaction',
            old_name='created_at',
            new_name='arrived_on',
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='banktransaction',
            name='desc',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='banktransaction',
            name='new_balance',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='banktransaction',
            name='unique',
            field=models.CharField(default='', max_length=64),
        ),
    ]
