# Generated by Django 2.0 on 2017-12-25 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lake', '0011_auto_20171225_0202'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='lvl_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='log',
            name='trade_session',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='lake.TradeSession'),
        ),
    ]
