# Generated by Django 2.0 on 2018-01-18 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lake', '0013_heartbeat'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='trading_pair',
            field=models.CharField(default='BTC-EUR', max_length=16),
        ),
        migrations.AddField(
            model_name='rate',
            name='volume',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='rate',
            name='volume_btc',
            field=models.FloatField(null=True),
        ),
    ]
