# Generated by Django 2.0 on 2018-01-18 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lake', '0014_auto_20180118_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='askprice',
            name='trading_pair',
            field=models.CharField(default='BTC-EUR', max_length=16),
        ),
        migrations.AddField(
            model_name='askprice',
            name='volume',
            field=models.FloatField(default=0),
        ),
    ]
