# Generated by Django 2.0 on 2018-01-18 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lake', '0015_auto_20180118_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='askprice',
            name='volume_btc',
            field=models.FloatField(null=True),
        ),
    ]
