# Generated by Django 2.0 on 2018-01-18 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lake', '0016_auto_20180118_1521'),
    ]

    operations = [
        migrations.RenameField(
            model_name='askprice',
            old_name='price_per_btc_eur',
            new_name='price_per_unit_eur',
        ),
    ]
